### ISSUE TITLE
cc-mode once does not expand correctly

### ISSUE THREAD

**Issue by broncodev** [AndreaCrotti/yasnippet-snippets#181]
Hello. Thank you for the collection of snippets.
I am having a bug with cc-mode once: when I try to complete the snippet with C-S-i (see configuration below), I get the following:
```
#ifndefY_H}
#define 



#endif /*  */
```
And I see the following line in the *Messages* buffer
`yas--snippet-parse-create: Wrong type argument: char-or-string-p, (stringp nil)`

I looked into the snippet, and tried to debug. So, I went to *scratch*, and I get an error with this:
`(file-name-sans-extension (buffer-file-name))`
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-nondirectory(nil)
  file-name-sans-extension(nil)
  eval((file-name-sans-extension (buffer-file-name)) nil)
  eval-last-sexp-1(nil)
  eval-last-sexp(nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```
Which seems to be relevant only when the buffer is not saved. When the file is saved, the name does appear next to `ifndef` (without space in between), but it is not expanded in the rest of the snippet, and hitting tab does not move the mark to the next tag.

I also have this in *Warnings*
```
Warning (yasnippet): Couldn't find: "[[:space:]
]*#ifndef[[:space:]
]*TEST_H}[[:space:]
]*#define[[:space:]
]*#endif[[:space:]
]*/\\*[[:space:]
]*\\*/[[:space:]
]*\\(\\)[[:space:]
]*#endif[[:space:]
]*/\\*[[:space:]
]*\\*/"
```

If I knew how to fix it, I would propose a solution, but I am really not good with lisp. I tried with an actual file and a new c-mode buffer. Also, I don't know if this has to do with the snippet alone or yasnippet as a whole (may be related to https://github.com/joaotavora/yasnippet/issues/784).

My configuration (running emacs -Q):
emacs GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.4.2)
yasnippet-20170326.1030 from melpa

.emacs (init file)
```
(require 'package)
(package-initialize)
(require 'yasnippet)
(define-key yas-minor-mode-map (kbd "<tab>") nil)
(define-key yas-minor-mode-map (kbd "TAB") nil)
(define-key yas-minor-mode-map (kbd "C-i") nil)
(define-key yas-minor-mode-map (kbd "C-S-i") 'yas-expand)

(add-hook 'prog-mode-hook 'yas-minor-mode)

(require 'function-args)
(add-hook 'c-mode-common-hook (lambda ()
                                (function-args-mode) ; Find definitions in current buffer
                                (setq tab-width 4) ; set tab width to 4
                                (auto-fill-mode) ; break long lines
                                (yas-minor-mode) ; activate yasnippet
                                ))
```

**Comment by npostavs** [comment]
> Which seems to be relevant only when the buffer is not saved.

That seems to be a bug in the snippet where it assumes the buffer is visiting a buffer. Should be fixed by using the empty string in this case:

```diff
--- i/cc-mode/once
+++ w/cc-mode/once
@@ -1,7 +1,7 @@
 #name : #ifndef XXX; #define XXX; #endif
 # key: once
 # --
-#ifndef ${1:`(upcase (file-name-nondirectory (file-name-sans-extension (buffer-file-name))))`_H}
+#ifndef ${1:`(upcase (file-name-nondirectory (file-name-sans-extension (or (buffer-file-name) ""))))`_H}
 #define $1
 
 $0

```

---

> When the file is saved, the name does appear next to `ifndef` (without space in between), but it is not expanded in the rest of the snippet, and hitting tab does not move the mark to the next tag.
> 
> I also have this in `*Warnings*`

Is this after you hit <kbd>space</kbd> in the first snippet field? That seems to be another variant of joaotavora/yasnippet#794 (which is caused by the fix for joaotavora/yasnippet#784).

**Comment by npostavs** [comment]
> When the file is saved, the name does appear next to `ifndef` (without space in between), but it is not expanded in the rest of the snippet, and hitting tab does not move the mark to the next tag.
> 
> I also have this in `*Warnings*`

Should be fixed by joaotavora/yasnippet#798

**Comment by broncodev** [comment]
Yep, this is fixed. Thanks! I leave this for someone who may want to tweak the snippets: you can change the length of the comment line by changing 79, 78 and 77 in the snippet file to n - 1, n - 2 and n - 3 (substitute n by your desired length).

**Comment by broncodev** [comment]
Nope, sorry. I still have issues (not only with myself ;) ) . 

When I hit the `yas-expand` (`C-S-i`), I can now go out of the snippet, and I have the name of the file, but in this way:
```
#ifndefT_H}
#define 



#endif /*  */
```
If I start typing, what I type is reproduced after `#define` and `/* `, but the T_H (the name of the file is t.h or t.c) stays in the first line.
Looking at the commentline snippet for prog-mode, I saw that it has `$( ... )` instead of \` ... \` . I replaced those characters, and I get something like this:
```
#ifndef T
#define 



#endif /*  */
```
where I can type again after `#define`, and what I type is reproduced in the last comment.

This is a minor bug, as you know, and I only report in case that you want to fix it. I am already satisfied with the snippet as it is

**Comment by npostavs** [comment]
Hmm, works for me. After expanding the snippet I get:
```
#ifndef T_H
#define T_H



#endif /* T_H */
```

**Comment by broncodev** [comment]
Yes, it's solved. I'm truly sorry for the delay. Thank you very much!
